name: Deploy
on:
  push:
    branches:
      - main








      
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          index.rubygems.org:443
          objects.githubusercontent.com:443
          rubygems.org:443

    - name: Checkout repo
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Install Ruby 3.0
      uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
      with:
        ruby-version: "3.0"
        bundler-cache: true
    - name: Install toys
      run: gem install --no-document toys
    - name: Lint
      run: "toys ci --only --test-rubocop"
